$(document).ready(function(){
    $(".close").on("click",function(){
        $(this).parent().hide();
    })
    console.log("start")
    $(".pic-15").on("click",function(){
        $("#trans-confirm").show();
        console.log($("#trans-confirm").find(".p1").html())
        $("#trans-confirm").find(".p1").text("30")
        console.log($("#trans-confirm").find(".p1").html())
    })
    $("#S1-light").on("click",function(){
        $("#S1-light").attr("src","..\\img\\T5暗.jpg");
    })
    $("#S1-light").on("dblclick",function(){
        var x=$("#S1-light").attr("src");
        console.log(x.replace(".jpg",".png"))
    })
    // btn
    $("#btn-panel").on("click",function(){
        $(".panel").show();
        $(".skill").hide();
        $(".gear").hide();
        $(".transcend").hide();
    })
    $("#btn-skill").on("click",function(){
        $(".panel").hide();
        $(".skill").show();
        $(".gear").hide();
        $(".transcend").hide();
    })
    $("#btn-gears").on("click",function(){
        $(".panel").hide();
        $(".skill").hide();
        $(".gear").show();
        $(".transcend").hide();
    })
    $("#btn-trans").on("click",function(){
        $(".panel").hide();
        $(".skill").hide();
        $(".gear").hide();
        $(".transcend").show();
    })
})